main:
  - name: Bio
    url: /
    weight: 10
  - name: Projects
    url: /#projects
    weight: 20
  - name: Publications
    url: /#publications
    weight: 30
  - name: Contact
    url: /#contact
    weight: 40

